### ISSUE TITLE
Add ability to increase "thickness" of indent lines.

### ISSUE THREAD

**Issue by Js-GitHub** [SublimeText/IndentGuides#4]
Please add ability to set the "thickness" of the indent lines.

Preferences > Settings - Default shows following; however, there is no width setting in the theme.

    // The color and width of the indent guides may be customized by editing
    // the corresponding .tmTheme file, and specifying the colors "guide",
    // "activeGuide" and "stackGuide"

![set-width-indent-lines](https://cloud.githubusercontent.com/assets/10727620/13394908/1d19872c-dea0-11e5-870f-be3571dbc6a0.PNG)

It says the color and width; however, I don't see any width options for activeGuide nor stackGuide in .tmTheme file:

![set-width-indent-lines-theme](https://cloud.githubusercontent.com/assets/10727620/13395034/fd078b54-dea0-11e5-984b-ca58bfb1f1d8.PNG)

**Comment by FichteFoll** [comment]
That's because they don't exist. Glad to be proven wrong otherwise.

**Comment by Js-GitHub** [comment]
What code or files determine where indent lines are drawn?  What files or code creates indent lines and fact that they align with tabs.

**Comment by FichteFoll** [comment]
Indent guides are drawn by ST internally. You can only modify the colors they are rendered with (what is in your color scheme), whether they are drawn at all (see related setting(s) in default preferences) and the frequency (`tab_size` setting), if you are using spaces.

**Comment by Js-GitHub** [comment]
Thanks

**Comment by plutonium-239** [comment]
@Js-GitHub Yeah this is 5 years old but I found out from another [thread](https://github.com/sublimehq/sublime_text/issues/2126) that you can at least have solid indent guides using `"solid"` in the `"draw_indent_guides"` options list (so that it would look like):
```
"draw_indent_guides":
[
    "draw_active", // or "draw_normal"
    "solid"
]
```
